export const testimonials = [
  {
    name: "Iylia Hani Rostam",
    image: "/testimonials/iylia.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Iylia-Hani-Rostam-testimonials",
    para: [
      "My first internship experience has been very useful in increasing my confidence and my thinking skill. The accounting internship has greatly broadened my knowledge in financial matters. My internship companies are Consurv Technic (M) Sdn Bhd and Dyna Segmen Sdn Bhd. Both companies are involved with the oil and gas industry.",
      "Based on my experience, these companies are not big companies like ExxonMobil, Shell, or other giant companies. But the experiences that I gained are more than I got rather than other students who take their internships at those companies. Basically, I've learned a lot where I involved in almost all matters. For example, I involved with financial matters, human resources, database, installation, documentation, and others. Some of my friends did not gain the experience as what I gained. This is because their supervisors or their top management already set for them what are the activities they should be involved in.",
      "The environment of this company is also flexible where if you come early to the office then you can go back early and vice versa. The staff and students are also very close, but we still have a professional border where we have to maintain. My supervisor treats us all the same; if I do something wrong, then he will advise me the same as to others. So from his advice, I always be as positive as I can because I know he wants me to be successful.",
      "This company also organizes family day, where we got to know each other better. So far, I have been to two family days and those two are very memorable. These family days are also an orientation session for the new interns. The most memorable family day that I joined with the company is a trip to Kapas Island. We joined the activity together, eat together, and everything is together. We are like a big family where we share everything together.",
      "My supervisor also trusts me. As what I learned it is hard to gain someone's trust in a short time, but not for this company. With just a few months at this company, I already learned the financial matter, the confidential matter, and others. Before I choose Consurv Technic (M) Sdn Bhd as my internship place, I already went to an interview at Permanis Company where the human resources manager told me that I will not learn all the details especially the confidential matter. So it's very different from Consurv Technic.",
      "The new environment also taught me to be independent and also to work hard. There is a huge difference between the working environment and study environment. In the study environment, we have a textbook to refer to, but in the working environment, we need creative thinking to find the solution to the problem. Fortunately, if I can't find the solution, I will refer to my supervisor or other staff as my last option.",
      "Sometimes, the tasks that my supervisor gives me are a lot and need to be settled in a short time. So what I learned is time management. Time management is very important in order to meet the deadline. So every task we get, we cannot delay it. When we manage our time wisely, we will make ourselves more organized. This is very important to make sure that everything goes with the flow based on what we set up.",
      "The other things that I learned at this company are to work hard and not to give up. This is what I adore about my supervisor. No matter how big the problems, he will try his best to solve the problem. For example, financial matter. As our company has many jobs and tenders to be completed, we need a lot of capital to fund each job. One of the major problems is late payment from clients where it actually affects our financial matter. So what my supervisor did was, he will try his best to find the capital either from his saving money, bank loan, and other. This is why I adore because he will not give up that easy.",
      "I am also given the opportunity to join BOSET training which is for offshore passport. Some of the companies will not allow the business students or information systems to join this program but my company allowed me to join this program. This is one of the new things I try and also it gives me more credit compared to other students.",
      "As a conclusion, all the experience that I gained from both companies taught me to be independent, to be a creative thinker, responsible, not afraid to try new things, and work hard to get what I want. Not only I learned a lot of new things but indirectly helped me to be a well-rounded person.",
    ],
  },

  {
    name: "Noor Shita Azizan",
    image: "/testimonials/shita.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Noor-Shita-Azizan-testimonials",
    para: [
      "My year kicked off with my industrial training when I reported as an engineering intern at Consurv Technic Sdn Bhd and in the blink of an eye I have completed my 32++ weeks here. This journey has been filled with ups and downs but it would have been almost impossible to complete without the help of certain individuals.",
      "First and foremost, I would like to thank my parents for their unwavering support and motivation they have given me to face the real challenges in life. All the lesson passed down by them certainly made me a stronger person.",
      "Boss, Managing Director of Consurv Technic have certainly played a very big role in my making my internship a wonderful experience. I am grateful as he showed his confidence towards me by choosing me into Consurv and not forgetting all the guidance, encouragement and all his efforts to make us, the interns and the staffs to come together as a family. I am also very thankful to Puek a.k.a my SV here and Anwar (former staff) for all the help and knowledge they gave me. At the very beginning, I never thought that I can survive 8 months here (because I knew that I am not the choice candidateL). I afraid that I can't managed my days here. Luckily, time by time I managed to do all on my own. My first week has been given task by Puek to do a website and the following weeks is doing HR apps. It is a tough work for me as I am a 'business' student. However, I managed to learn a lot during this period and learnt about PI as well. Thank you Puek and Anwar!!!",
      "My big applause to the other permanent staffs of the company, Nasrul, Amir, Cik Jihan, Mummy Linda, Umi Pain, Daddy Vin, Jane, Abu, Azfar, Zayne and others as well for their full assistance and advices. Next, my shout out goes to my ConsurvDyna Family where everyone has each other back. We work together and also have fun together. I am blessed to come across them in my journey as all them have different knowledge to be passed unto me. I am grateful for this beautiful friendship I have made throughout my time here. To all the staff of Dyna and Consurv Technic and the interns, thank you very much. I will remember all the memories and experiences that we shared together.",
      "My supervisor also trusts me. As what I learned it is hard to gain someone's trust in a short time, but not for this company. With just a few months at this company, I already learned the financial matter, the confidential matter, and others. Before I choose Consurv Technic (M) Sdn Bhd as my internship place, I already went to an interview at Permanis Company where the human resources manager told me that I will not learn all the details especially the confidential matter. So it's very different from Consurv Technic.",
    ],
  },

  {
    name: "Nursyazleen Syafiza",
    image: "/testimonials/syazleen.jpg",
    university: "Universiti Teknologi Malaysia (UTM)",
    course: "Human Resource",
    intern: "6 months",
    slug: "Nursyazleen-Syafiza-testimonials",
    para: [
      "At the very first place, I am been hired as an intern by Consurv Technic Sdn Bhd. Honestly, I do not know much about this company. Once I enter this company, I realized that there are two names of company working in one roof which are Consurv Technic Sdn Bhd and Dyna Segmen Sdn Bhd. In short, I can say that Consurv is about IT Software Development while Dyna more towards Oils & Gas Industries.",
      "Previously, I had an experience working as a part-timer in House Developer Industries. Currently, this is my first ever experience working in Oil & Gas Industries. Even though I am working only in administrative site, the work brings much different between these two industries. Thus, I gain a lot of experience.",
      "During my internship, I am not only doing the HR works. The most precious thing that I had learned is I had been given an opportunity by our boss, Mr Faiz Hussin, to undertaking engineering project. And with first trial, I won the project from Petronas Melaka. I learned a lot how to deal with client and suppliers. Also learn how to organize all the documentation preparing for project tender. Even though it is rigid and sometimes I am running out of time, deep in my heart I enjoy doing it.",
      "Another thing that I really enjoy in this company is the bond of friend relationship among the employees. I love making friends especially from engineering department as their teamwork is the best ever. They always be there for me whenever I am down and motivate me a lot. They also guide me a lot and transfer many knowledge to me especially when I have to do the procurement work which I have no experience before on it before.  We had a great time together with all the joking, laughing, teasing. And at the same time, learning from them.",
      "Last but not least, thank you for accepting me as a part of the family throughout this 6 months. I enjoyed it a lot. I do hope Consurv Technic Sdn Bhd and Dyna Segmen Sdn Bhd will move forward in the business related industries and making more profits from time to time. Success always!",
    ],
  },

  {
    name: "Mohd Noor Shawal",
    image: "/testimonials/shawal.jpg",
    university: "Universiti Kebangsaan Malaysia (UKM)",
    course: "Information Technology",
    intern: "3 months",
    slug: "Mohd-Noor-Shawal-testimonials",
    para: [
      "Alhamdulillah, that is the word that I am going to start for this testimonial. Thank god, I got a chance to meet all the wonderful and kind people at DynaConsurv. Since it was my first internship experience, when the first day I came in, I was so worried huhu because I used to watch a lot of dramas or movies where internship are being bullied by the staff hahaha.. But my first day being at DynaConsurv until the moment I write this testimonial, I haven't felt that way even at a single of time. All of them are like a family and treat each other like a family. If we are confuse about something, they will teach us patiently until we really do understand about something.",
      "Alhamdulillah also, from this internship experience also I got to gain my knowledge not only on IT-field as I am majoring in it, but also I got some basic knowledge on how are actually Oil & Gas industry working in Malaysia. Other than that, I also got to met a very superb IT-expert at Consurv which is Abang Fuad. He really taught me a lot of thing especially on basic knowledge of some programming language that I haven't learned at my university. Also, a day before our hackathon competition, he also gave us a simple but superb idea to face the hackathon the next day as our team (Afiq, Kak Wanie and me) were discussing about what we are going to presents at the hackathon.",
      "The best experience at DynaConsurv also, I got to meet a very talented Data Scientist, Kak Aqeelah. Through her, I got to explore some software like PI AF, Cisco, and also I got some basic knowledge on how to handle and sort data in excel as I am very bad at excel because I rarely used it. Also, Alhamdulillah got to meet a very experienced person like Boss and Nas really taught me on how to be a good leader. They are not just bossing around in the company but also 'turun padang' and teach me a lot of thing. They also really-really 'turun padang' when we are having a futsal or badminton, they played together with all the interns and staffs. This is the best way to make sure our bond in company is in a good and positive way through sports despite management level.",
      "Again, Alhamdulillah got to meet all the other interns and staff which is all are a good people from the moment I knew them until today. They are just so kind and humble, thank god haven’t being bullied even once hahaha Thank you semua!",
    ],
  },

  {
    name: "Siti Nur Sabrina Amran",
    image: "/testimonials/sabrina.png",
    university: "Universiti Teknologi MARA (UiTM)",
    course: "Computer Science",
    intern: "3 months",
    slug: "Siti-Nur-Sabrina-Amran-testimonials",
    para: [
      "Practical Training, or internship, is a compulsory subject to take to complete my diploma studies. I am extremely grateful that I got accepted in Consurv Technic. To start, I sent my resumes to many other companies before Consurv Technic in hopes of getting accepted for internship. I waited and waited until it was 4th of January. My internship should start on 6th of January. I was panicking for none of the companies I sent my resumes to wanted me, probably because I’ll be interning for only two months. I was so close to giving up and accept that I will just have to do my internship a lot later and watch my friends graduate before me. My friends encouraged me to keep looking, and then I found Consurv Technic. My boss, Faiz Hussin interviewed me through the phone and by some miracle, I was accepted. I am extremely grateful to my boss.",
      "Interning at Consurv Technic means I had to learn new things. I had to do website developing and learn about the industry. I had zero experience. It was challenging and I was struggling because I am a slow learner. However, I wasn't left alone to figure it out myself. I received help from the people here and I am very grateful for their guidance.",
      "As this internship was challenging, it was also fun. My internship here was not what I had expected. I imagined it to be either boring, or too serious. I didn't expect the people here to be so nice and friendly. The other interns and staff were outgoing and it made my internship days to be something I look forward to. I also didn't expect that I, an intern, would be joining the company trip. The company trip was very eventful and tiring, but memorable and made me closer with the others. Leaving so soon is my only regret. I will wish this company luck and to stay amazing.",
    ],
  },

  {
    name: "Nur Aisyah Nurhadi",
    image: "/testimonials/aisyah.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Nur-Aisyah-Nurhadi-testimonials",
    para: [
      "First and foremost, a big thank to Allah for allowing me to go through my internship experience in Consurv Technic and greatest appreciation to boss, Mr Faiz Hussin for accepting me. Yes I know it is not easy to get in here and the tasks given were not as easy as other interns were doing out there. I had a lot of sweet memories with colleagues in Consurv Technic. The support that I received, the knowledge that I gained, the skills and lesson that I learned made me feel very blessed to have them throughout my journey.",
      "The joy and fun throughout these seven months were the best moments I had in my life. Boss, Fuad, Syafiq, Adib, Nasrul, Kak Dqeen, Tidja, Amir, Linda, Jannah, En Jihan, Azfar, Dilla and internmates Rahj, Leroy, Razi, Thiban, Claire, and Pot were people who cheer my life. They were wonderful workmates as they never failed to support and made the company alive.I was excited to go to site visits since I had never had the opportunity to experience it before and I always wonder when my time will come.",
      "As a BIS student, the chance to go to site visit is a not-to-be-missed-experience and the first site visit I went to was at Tanjung Bin Plant together with Project Engineer, Amir. The unforgettable moment was when our hotel rooms were rushed by Jabatan Agama Islam and I never expected such 'surprise'! Thanked God nothing happened. The incident and the experience during the 4 days site visit was one of my valuable memories in Consurv Technic.",
      "Lastly, Consurv Technic is the best platform for those who want to gain knowledge and experience before going to real working life. The choices given to you should not be wasted as you will never get it in other place. Seize the moment and catch your dream!",
    ],
  },

  {
    name: "Alif Danial",
    image: "/testimonials/alif.jpg",
    university: "Universiti Teknologi MARA (UiTM)",
    course: "Computer Science",
    intern: "3 months",
    slug: "Alif-Danial-testimonials",
    para: [
      "It has been fun 9 weeks here at Consurv Technic (M) Sdn Bhd. I have learned a lot about app development, how a good API should be, general knowledge about oil and gas industry. I have also met new and interesting people here and some become my friend that I spent a lot of time together. The payment here is also good and always paid on time.",
      "For the most part of the internship, I was given the task of making a HR app for the company to allow staff to apply leave anywhere and anytime. I learn a lot of things while making this app. I have improved my javascript skills, better time management to meet dateline, and overall developing app for both android and iOS. In between I help with PI AF project, which help me to learn a little about the PI AF system Petronas is implementing.",
      "During my internship, I have made several friends within this company. The first person I made friend with is Izzah since she sits beside my cubicle. Through her encouragement, I made friends the other interns, Syawal and Hazwan, and the new staffs, Afiq and Wani. We often take lunch and hang out in the office when we're not busy. I also get to know better my internship partner, Dastur, about his strength and weakness while we were making the app together. Unfortunately, I don't have enough time to befriend all of the staff, but I must say the people here are very friendly, even the Boss.",
      "As far as payment goes, it is very good considering usually internship don't usually get payment and even so, not this many. The flexible time is very convenient as you can come at what time you feel comfortable if you complete the 9 hours' requirement. You can gain extra money if your RFQ succeeded and made profit but I have no such luck. In summary, I'm happy that I choose this company to do my internship. I hope that this company continue to prosper in the future. The memory I made here I will remember for very long time. I'll end this by saying “there is no reward without a challenge”. That's all from me.",
    ],
  },

  {
    name: "M Yahya Mahmoud",
    image: "/testimonials/yahya.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "M-Yahya-Mahmoud-testimonials",
    para: [
      "When I first got here, I didn't expect anything from this company beside doing my work and moving on after my internship, just like most of my friends who did their internships before me in different companies and different sectors and industries, and I couldn't have been more wrong!!!",
      "The last 8 month of my life were very different from the stories I have heard from my seniors, They talked about their stubborn supervisors, the “Photostatting” jobs, the boring work atmosphere, and all the crap they got from their clients, but what I have experienced is very different, I did Photostatting but only when it was my Project, if the work atmosphere was more fun than this , I think we'd had to actually pay to be here, and I don't think I need to tell you about my boss because if your reading this you already met him and realized how cool he is J.",
      "People Might think a big company is better, and you would learn more there, and these people can't be more wrong, Do you think Petronas or shell or SLB will send you offshore as an Intern? NO, Do you think Accenture, KPMG or frost and Sullivan would allow you to look into client’s confidential financial records? HELL NO, Do you think Microsoft, IBM or Google will actually allow you to use their resources to try new things? NO, Okay maybe Google will. My point is the experience you'll get here is way more valuable than how to setup the Xerox machine inKPMG to scan 2 sided Pages (you'll learn this here too if you are worried about that).",
      "During my internship I made a lot of new friends around here in Dyna and Consurv, and it wasn't all about work, We do a lot of activities together like Bowling, movie night, Karaoke, plus of course the bi-annual Trip. So we’re kinda like a big family, you don’t get that anywhere else, and believe me, it’s priceless.",
      "Good Luck J",
    ],
  },

  {
    name: "Norsyuhada Mostar",
    image: "/testimonials/ada.jpg",
    university: "Universiti Teknologi MARA (UiTM)",
    course: "Information System",
    intern: "5 months",
    slug: "Norsyuhada-Mostar-testimonials",
    para: [
      "First and foremost, my deepest gratitude to DynaConsurv team to have given me the opportunity to be a part of this amazing experience. I consider myself as a very lucky individual as I was provided with an opportunity to be a part of it. I am so grateful for everyone from DynaConsurv with their constant guidance and never-ending support during my five months being here and that includes Aca, Fuad, Aqeelah, Wani, Pain, Vin, Nabil, Fariz, Nas, Nisa, Abang Man as well as the finance department team; Mina, Linda, Zahir and En Jihan. Each and every one of them have guided me or provided me support at least once. Not to forget, my co-interns; Zul, Qayyum, Meon, Gek and Izzat which I have perceived as my brothers who were always there for me and protected me during my training period. I will never forget everyone I met here.",
      "I will never forget the interns' session, my pitching exercise for PETRONAS Lubricants and the nervous feeling I had when I had to present for the ECG Machine to our client with all the big bosses around. But still, it was all an eye-opening experience and I am thankful that I got to grasp the opportunity. Being at DynaConsurv has made also me become more confident and bolder. Even though it is a small-sized company, it offers many benefits to my career such as more visibility, experience in variety of areas, increased flexibility and it offers an entry-point to the industry. Interns get to wear several hats, interact with staff more often and able to afford a 360-degree view of company-wide operations. It is also easy to interact with Director and the decision makers. Because I’ve done many roles in the company, I was able to gain knowledge and insight beyond my area.",
    ],
  },

  {
    name: "Fairuz Husna",
    image: "/testimonials/fairuz.png",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Fairuz-Husna-testimonials",
    para: [
      "I was ecstatic that I finished my 7-month internship at Consurv Technic without the idea of giving up. I was quite satisfied with the working life experience that I gained throughout the period especially with the fact that I learned to overcome most of my limitations. Given that I am afraid of heights, I did what I had to do to make it happen when I was assigned to work at heights. Consurv exposed me to the reality of working life because they never treat us like an intern but a real employee. Furthermore, I learned how to handle myself during sessions with clients even though I always get so nervous during meetings. I really enjoyed road trips during site visits as it gave me the opportunity to travel to other parts of Malaysia. In fact, I love working on site more than in the office.",
      "It was nerve-wrecking at first working as an engineer as it is not easy - making people listen to you as well as being the expert in the subject matter. However, other employees at DynaConsurv especially my intern mates helped me a lot during tough times, and we worked like a family. That is what I love the most about this company.",
      "In addition, it was a bonus to have a great working environment. Consurv has very flexible working hours. Even though the workload was heavy, my Consurv family never failed to cheer me up every day. I really enjoyed my time staying late in the office just to hang out with them by playing cards, watching movies, chit chatting and sometimes helping other employees pack their stuff for site visits. I will really miss every moment with them.",
      "I would like to thank all of you for being so good to me and for being so understanding and sensitive towards my feelings and needs. I will never forget each one of you who have been part of my awesome internship life. You all taught me something that I can treasure for life. This is not goodbye yet since I am sure I would not be getting over Consurv anytime soon and I will surely visit all of you again.",
    ],
  },

  {
    name: "Siti Noor A'tiqah Manan",
    image: "/testimonials/siti.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Siti-Noor-A'tiqah-Manan-testimonials",
    para: [
      "Here, I, Siti Noor A'tiqah Binti Manan, the student of University Technology PETRONAS as well as a Muslim, would praise the God for His blessings and guidances towards me in this whole life. Also, praise for Him for blessing me to go through the Industrial Internship Programme successfully at both companies, Consurv Technic (M) Sdn Bhd and Dyna Segmen Sdn Bhd.",
      "Priceless appreciation from me to Mr Faiz Hussin, Managing Director for accepting me as a trainee for 32 weeks in this company and to be my best role model. I have learned a lot from him especially to be a tough and committed person in real working life and also in our real life. Without the awareness that given from him, I think I will keep on to be someone that not confident with myself. I also want apologies, because I bring lots of problems to this company since my father was ill and always on leave.",
      "Millions of thanks to my Accountant Supervisor, Ms Hafizah for guiding me tirelessly during my training. She has taught me a beneficial knowledge in accountant as well as database. I have shared a wonderful experience when I working under her and I feel very fortunate because I got supervisor that very tolerance. Thank a ton to Mr Nasrul Annuar, Dyna's Project Manager that has helped me a lot in order to handle tenders and manage problems that occur during the tender process.",
      "Last but not least thanks to my colleagues as well as trainees at Consurv Technic and Dyna Segmen, Mr Kamil, Mr Rafie and Mr Azizi for the supports either directly or indirectly. Not to forget, the new comers, Mr Adib, Mr Azlan, Mr. Yahya and Ms Hazilah. Thank you for all your support.",
      "As conclusion, it has been a pleasure to work with all of you with full support and cooperation. I am very sorry for my mistakes, misunderstandings and anythings that come out bad from me and I regrets it. Once again, thanks to you all.",
    ],
  },

  {
    name: "Aaron Ng Tong Wu",
    image: "/testimonials/ngtonwu.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Aaron-Ng-Tong-Wu-testimonials",
    para: [
      "“Hello, is this Ng Tong Wu? Do you know you are supposed to be here for your interview now at the Registry office?” a lady with a stern voice said. This is the sentence that greeted me when I answered a call that woke me up from sleep. I don't even know who is the interviewer and just rushed to the interview room, at the same time, doubting that it's a prank call.",
      "What's waiting for me in the interview room was even more surprising. After a few minutes of chit chat about my IT knowledge and experience, the interview turned into an interrogation of my personal and love life. And miraculously, I was asked to join Consurv by the end of the 10minutes interrogation. I still don't know whether my IT knowledge or personal/love life makes boss thinks that I am worthy to join Consurv.",
      "During my internship with Consurv, I have learned to not only become a system admin and technical support, but also a site engineer for Dyna Segmen, delivery guy(PPE), party planner, project manager, and many more. The real life working experience gained definitely worth much more than the knowledge gained in lectures.",
      "I would like to express my gratitude to boss for giving me the opportunity to grow with DynaConsurv. I must extend the appreciation to everyone at DynaConsurv for their helping hand and please forgive me for all my faults and unintended racist insults. Well, more than 6 months of working experience at DynaConsurv has seen many staffs coming and going, Zaza, Fatin, Ima, Aliff, Kalai, Alia, and Isaac. This is the culture of DynaConsurv (not to forget racism in the company). Don’t be sad that we are parting but cherish the moments that we have spent together. Hope that when our path cross again in future will see that we have grown into a much better person. My sincerest “thank you” to Consurv Technic and Dyna Segmen.",
    ],
  },

  {
    name: "Noor Farhana",
    image: "/testimonials/farhana.jpg",
    university: "Universiti Teknologi Malaysia (UTM)",
    course: "Human Resource (HR)",
    intern: "6 months",
    slug: "Noor-Farhana-testimonials",
    para: [
      "“Among 5 of you, who should I choose?”. I still remembered the question asked by boss during my interview session and I am confidently answered “me!”. The following week, I got the offer for internship placement at Consurv Technic Sdn Bhd. It surprised me as I think I’m doing badly in the interview session and I thought other candidates more eligible.",
      "During my 24 weeks attachment at DynaConsurv, I have been assigned with plenty of works which related to my educational background. From HR related work, documentation, database and sending RFQ if I was assigned for projects. Im not saying that all the task were easy, but at least I learned a lot and thanks to Boss for these experiences. All the staff treat me the same way and they will advise me if I do something wrong and how to perform better in doing my job. The tasks given teach me on how to work under pressure and also time management. Every time I got new tasks, I must set the dateline so I will able to complete it within the time frame. Without the continuous support from Boss and my supervisor (Fik and Nina), I may not be able to survive my internship program at DynaConsurv.",
      "Frankly speaking, I really enjoy working at DynaConsurv with the friendliest and helpful staffs ever. My highest gratitude goes to our big boss, En Faiz, who believed in me and give me this opportunity (Thank You, Boss!!). To all the staff and intern of DynaConsurv (Nas, Fik, Nina, Fuad, Adib, Amir, Linda, Jane, Azfar, Zihan, Grey, Aaron, Lee, Sofea, Kun, Kin, French, Kerol, Armenio, Alden, Adam, Fiqa, and Shodiq) thank you for always helped me when I need the most. To all new staffs and interns, good luck.I wish all the best to DynaConsurv and always strive for excellence!",
    ],
  },

  {
    name: "Nur Zarith Sufia",
    image: "/testimonials/zarith.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Nur-Zarith-Sufia-testimonials",
    para: [
      "All praise due to Him, the most merciful for giving this opportunity to successfully complete my industrial attachment with Consurv Technic (M) Sdn. Bhd and Dyna Segmen Sdn Bhd for a period of 28 weeks. I am glad to express my utmost appreciation to those who have helped me throughout my practical training. Special acknowledgement to Mr Faiz H. Hussin, Managing Director of Consurv Technic (M) Sdn Bhd.",
      "When I was about to start seeking for the placement of the industrial internship, I was promised to myself to find the company that would really immerse me in the real working environment as I am confident not all company will treat trainee as part of their family.",
      "In UTP, we have only one semester for the student to fully utilize the duration to absorb as much of the knowledge and experience. I would say that the decision to choose the company for our training is crucial for the betterment of our study as this is the only period that being allocated to us to apply the theoretical knowledge that we learned during our study.",
      "Personally, the very first day of my internship was a hectic day. I have been assigned to continue some of the projects of the previous intern and it was so challenging to cope with the current status of every project. I need to fully understand what the project is all about and who I need to contact pertaining to the respective issue that occurs during the execution. To be able to handle these projects, time management is really important. We have to segregate and prioritize the workloads in order to be multi task person. What makes the situation getting harder is that, I am a new comer and I don't know who I need to refer regarding to some matter occurred.",
      "Surprisingly the environment of the office was not as what I expected! The staff and trainee were so closed and there is no double standard applied in the company. Whenever I face obstacles during the execution of the project, they would lend their hand to help me or giving the ideas on how to solve the problems. Thank you to my supervisor, Managing Director of Consurv Technic, Mr Faiz Hussin who always put trust to me to execute the project which I believe not all company will take the challenge to give the opportunity for trainee to handle the company’s project. My gratitude to the Director of Consurv Technic, Ms Nur Hafizah who always being a good listener and encourage me to be confident to handle some issues and Mr Nasrul Annuar, the Project Manager of Dyna Segmen who always have brilliant idea on how to win clients' heart and be professional in handling the problem occurred.",
      "As a conclusion, I enjoyed my industrial internship as it equipped me with the knowledge that never being taught in the university (integrity, respect others, being multi task person). I fully utilized the industrial internship period as I believe if I feel tension and pressure with the workloads, it proves me that I am working and learning. Not only doing training",
    ],
  },

  {
    name: "Haziq",
    image: "/testimonials/haziq.jpeg",
    university: "Universiti Teknologi Malaysia (UTM)",
    course: "Computer Science (SE)",
    intern: "6 months",
    slug: "Haziq-testimonials",
    para: [
      "Before applying to Consurv Technic for the Software Engineer internship, I didn't have an idea of what my dream internship would be like. After interning here, I can say Consurv has set the bar pretty high for other internships to beat.",
      "The internship opportunity I had with Consurv was a great chance for learning and professional development. Therefore, I consider myself as a very lucky individual as I was provided with an opportunity to be a part of it. I am also grateful for having a chance to meet so many people and professionals who led me through this internship period. I have gained a wealth of knowledge about many different things from the Consurv staff, and the amazing people Consurv has put me in contact with during this internship. They really want their interns to have an exceptional learning experience while interning here and really take the time to plan around it.",
      "The Consurv staff is very professional and highly organized, but also some of the friendliest people you will ever meet. Overall, a great thankful to Consurv colleagues because they willing to accept me as a part of their big family. They treated me well and always made the environment joyful.",
    ],
  },

  {
    name: "Akmal Ridhwan",
    image: "/testimonials/akmal.jpg",
    university: "University: Asia Pacific University (APU)",
    course: "Information Technology",
    intern: "2 months",
    slug: "Akmal-Ridhwan-testimonials",
    para: [
      "A one page testimonial is not sufficient to describe my internship experiences with DynaConsurv. I had been working at DynaConsurv for approximately two months and all I can say is that it was one of the most memorable time of my life. The first week of work was difficult because of the transition of university to working life. But I adapted and settled in quite fast as the staff (including interns) here made sure I was comfortable. One thing I absolutely love about working here is that everyone is always there for you no matter how busy they are. You do not just work, you create friendships here.",
      "DynaConsurv gives you pressure, no doubt about that. But at the same time, it teaches you how to handle it. Pressure is always there no matter which industry you work in. Pressure lifts you up, makes you stronger and evolves you into a solid individual. That is exactly what DynaConsurv had transformed me into. It prepared and provided me with a solid foundation to be successful in the working world.",
      "DynaConsurv is a great place to learn for individuals who are interested in the Oil and Gas industry. I once thought that students with non-science degrees would never be engineers. But I was clearly wrong! At DynaConsurv, everyone is an engineer. I am doing a degree in Information Technology and working as an engineer in the Oil and Gas industry. How cool is that?! It has always been a dream of mine to be an engineer. The bottom line is, DynaConsurv makes dreams come true.",
      "Thank you very much Mr. Faiz, staff and interns who had clearly made my two month journey here very memorable. Thank you for the lovely company trip to Janda Baik, It was an exciting journey and I wish DynaConsurv and all of its employees the best in their future endeavors. “If there was one word to describe DynaConsurv, it would be family.",
    ],
  },

  {
    name: "Nur Nabilah Taib",
    image: "/testimonials/nabilah.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Nur-Nabilah-Taib-testimonials",
    para: [
      "First and foremost I would like to express my gratitude to DynaConsurv for accepting me as part of company. Thank you to Mr. Faiz for giving me an opportunity to learn and be familiar with industry before my real future working environment. Thank you to all staff to support and helping me in order to sustain the company objectives.",
      "During the interview session, Mr Faiz clearly mentioned Consurv Technic is just a small company but you definitely you will learn a lot.” As for me, I am more interested on how much I will learn through out 7 months of internship rather than how big your host company is. Honestly, I prefer small company to pursue my internship because of the working environment and the workload. Maybe some students like to become a part of multinational company but most of them complained because the top management put them only in small discussion and tasks due to confidential and lack of confidences in them.",
      "In contrast, I, myself handled from A to Z and from small project to big project which involved big companies such as Petronas, MTBE, Shell and others in Consurv Technic Sdn Bhd. Thank you to Mr Faiz who has confidence on me to manage company's project through out the internship period. He never gave up to advise and gave a though whenever I got stuck in the middle of project execution.",
      "Other than that, I had an opportunity to attend OGSP training which usually only involve Engineering students. From that training, I learned and observed the working environment in plant and the safety.",
      "The most excellent experience is during working travel to MTBE, Gebeng with my supplier for a few days. Even though, it was a first met between supplier and me, due to professionalism, we managed to work smoothly and our clients were fully satisfied with our performance.",
      "As a conclusion, I guarantee that every intern will not regret to choose Consurv Technic Sdn Bhd as your host company to build up your skills and personal characteristic.",
    ],
  },

  {
    name: "Ahmad Kamil Zanial",
    image: "/testimonials/kamil.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Ahmad-Kamil-Zanial-testimonials",
    para: [
      "From bottom of my heart, I would like to express my gratitude to Consurv Technic Sdn Bhd and Dyna Segmen for being my host company. Thanks for the opportunity and trust that they give to me to become one of internship students here. It all began with simple pieces of resume and straightforward interview. Few weeks later, I received the offer letter from Consurv Technic with full of excitement. I swear on myself that I will try myself to perform the best that I could in order to satisfy the every single need of company.",
      "Now, it comes to the end of my internship, I feel sad very when I recall all the memories start from the first day I am here.  My special thanks goes to all staff (Mr. Faiz Hussain, Mr. Nasrul Annuar, Mdm. Hafizah and Mr Sohpian) and my fellow friends (Azizi Wahidi, Rafie, Atiqah, Adib, Azlan, Hazilah, Yahya and Yasha) that help me a lots while facing some difficulty and cheer me up when I feeling down. Thanks all for being my special friends as most time we spending together as part of family.",
      "I also would like to thanks Consurv Technic and Dyna Segmen as given me lots of experiences and knowledge that is valuable for me. Also I want to show my gratitude for Consurv Technic and Dyna Segmen for changing my attitude and way of thinking in becoming a better person, the person that is more responsibility, hard work, and independent.",
      "At last, I would like to ask for forgiveness if I made mistakes and fault that I unintentionally done.  I wish for the best for Consurv Technic and Dyna Segmen for the future.",
    ],
  },

  {
    name: "Hazwan Haliff Hishamudin",
    image: "/testimonials/hazwan.jpg",
    university: "Universiti Kebangsaan Malaysia (UKM)",
    course: "Information Technology",
    intern: "3 months",
    slug: "Hazwan-Haliff-Hishamudin-testimonials",
    para: [
      "I was interning at Consurv Technic as an IT intern. This company focus mainly on oil and gas industries. They also have sibling company called Dyna Segmen for the engineering department. I like how interns are treated just like full time associates and get assigned actual and meaningful tasks which are crucial and beneficial to the IT department. It feels great to be a part of the actual IT department team. Even though I only joined the team for two months, I still felt a strong sense of achievement after doing my first project. The best part of the internship was the company meeting and the weekly sport events. Internship were also invited for the company meeting and during that time especially we gain a lot of input. The time spent working for project with other interns from various departments form some of the most memorable parts of my internship.",
      "I would like to thank our boss Mr Faiz for allowing me to conduct my internship in this company. I gained deeper insights into the oil and gas industries and it has helped me significantly in my career planning.  I developed a better understanding of the career path of an software engineer through the internship, helping me to make an informed career decision. I would also like to thank my IT manager Mr Fuad for all the guidance he gave me during project development. Thank you to my friend and Consurv Team Shawal, Afiq, Wani, Dastur, Alif for their cooperation and time spent together, everyone in Dyna Segmen and everyone in the company for all the guidances. I am very satisfied with my internship in Consurv Technic, and I would like to thank you for the advice and the guidance everyone gave me.",
      "This week was my last week. I absolutely wanted to thank you for this opportunity. It was an amazing experience both from a personal point of view and from professional point of view. I am going back with more knowledge on software system and workplace experience, but most of all with memories and unforgettable encounters. The internship is very good, a lot of work and a lot to learn. Thanks!",
    ],
  },

  {
    name: "Nur Dalilah M Azizi",
    image: "/testimonials/dalilah.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Nur-Dalilah-M-Azizi-testimonials",
    para: [
      "My internship at Consurv Technic (M) Sdn Bhd provided me with valuable hands-on experience and a better idea about what knowledge areas and skills I should attach more importance and make further improvement to in my further studies. Other things that I have valued most about my internship here include, but not limited to, the nice and supportive working environment. It was a wonderful opportunity to learn and get better understanding of the culture of the company. I also benefitted from attending the events and have enjoyed the friendship with my colleagues that was developed during my time working here.",
      "It has given me the opportunity to see so much more about the Business field than I am able to learn in UTP. I have developed many skills and have a much greater concept of what to expect after university life. My internship has given me a greater understanding of what it is I have learned in the class, and given the opportunity to apply it to real situations. One of the greatest benefits that I have received is the knowledge that I actually enjoy doing what it is I have been studying for and also given me the courage to start something from scratch and, with hard work and diligence.",
      "One thing that really stands out about this internship is that we are never treated as just interns, we are encouraged to think and act like the full-time employees we strive to become. This means that you “own” your projects and have full autonomy on how you want to run your works which is an incredible feeling of accomplishment. However, that doesn’t mean you’ll be a lone wolf either. The team is a tight-knit, supportive group of brilliant staffs who are always ready to help each other and help you, and I’ve gained some incredible mentors in the process. They’re also a fun group and our day-to-day include group lunch outings.",
      "Lastly, special thanks to Mr. Faiz Hussin for giving me the chance to work as an intern here in Consurv Technic.  I also would like to take this chance to express my gratitude to all the wonderful people here for making my work life incredibly meaningful.",
      "If you are looking for an internship where you can get by with small, menial tasks here and there, this is not for you. But for those who want to dive into interesting projects, make real impact, constantly think outside the box, and learn what it takes to be an effective employee, this internship will constantly challenge you and you will feel pumped to go to work every day to learn a lot and contribute to this great company.",
    ],
  },

  {
    name: "Anif Adenan",
    image: "/testimonials/anif.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Anif-Adenan-testimonials",
    para: [
      "Everybody make choices in their life. Theses choices sometimes lead them to a greater height, open doors of opportunities. This is what happened to me. Since I stepped in UTP, Oil and Gas industry has always been my favourite, but somehow, there is a missing link. Yet I don’t really know what it is. My internship at Consurv and Dyna made my passion about Oil and Gas, a dream comes true. It changes almost everything. I got to know a lot of things about the industry. I was exposed to the business environment exponentially by the boss, Mr Faiz H. Hussin. He is a very experience man whom I think every supervisor in host companies should act and become.",
      "I always believe that everybody has different way on how to acquire knowledge, and mine is a little bit different. The way it works in the company is the pressure gets you going and when the going gets tough, the tough gets you what you wanted to become. It is just the matter of time and perseverance.  You can’t really expect what you will learn in the company, it keeps coming and pours unto you like the Niagara fall. As interns are all very welcome in the company, I would really appreciate the teachings and advice. Special thanks to the Big Boss of Consurv,  Mr Faiz Hussin, and the whole Dyna Consurv family, Mr Nasrul Annuar, Ms Fizah and Zaza. Thanks for the opportunity, thanks for the love. Cheers!",
    ],
  },

  {
    name: "Muhammad Dastur Mohd Zabid",
    image: "/testimonials/dastur.jpg",
    university: "Universiti Teknologi MARA (UiTM)",
    course: "Computer Science",
    intern: "3 months",
    slug: "Muhammad-Dastur-Mohd-Zabid-testimonials",
    para: [
      "As practical training is near, I was anxious on getting into a company and finding a place to stay to pass this compulsory practical training subject for computer science course in UiTM. I’m also worried about how I would perform under a company knowing that I’ve never had working experiences. I’m just a boy taking a diploma in computer science who’ve done nothing but sitting on his chair accompanied with a desk and a laptop in front of his face learning and doing assignments.",
      "A lecturer from my university recommended Consurv Technic Sdn. Bhd. to me as they offer the highest allowance for industrial training. I became so eager to apply this company not because of the allowance but seeking good knowledge and experiences for self-improvement to become an excellent programmer (please believe me). The interview part was unexpected. I got interviewed by the boss on a random day and time without being notified first. He asked some good looking questions and I replied with some good looking answers (considering grammars) costing time of good thinking which exactly the same for this testimony.",
      "Fate has brought me here and I'm grateful for that. I was happy and slightly relieved the moment I receive an acceptance letter from the company. In my mind, I’m wondering what kind of computer skills and knowledge that I’ll gain but not RFQ. I’ve learned a lot of things from this company such as getting used to the working environment especially RFQ. I failed for the first time doing RFQ, but that’s where I’ve learned and luckily, I managed to get PO after that. RFQ is fun and I want to do more but unfortunately my time here is just two months. The major thing that I do in Consurv Technic is learning and making mobile application to be used among the staff of DynaConsurv using nativescript. Nativescript is a javascript language framework for developing native iOS/Android mobile application. It’s my first time developing a mobile app and I enjoyed exploring, diving deep into the web. I want to say thank you to my boss, Mr. Faiz for giving me a chance to become a part of the company and also Fuad, Aisyah, Pain, Aqeelah and my friends for always giving me support and help when I needed. It was a great internship experience. Yes, I know this a long boring cliché paragraph.",
      "Boss once asked me to share a 'Wow' experience during my interview. I didn't really know the answer but now I know this internship is definitely that ‘Wow’ experience for me. HRapps will be my parting gift to the company. I promise that I’ll make a good use for what I’ve gain from Consurv Technic in the future.",
    ],
  },

  {
    name: "Sofea Azrina",
    image: "/testimonials/sofea.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "7 months",
    slug: "Sofea-Azrina-testimonials",
    para: [
      "DynaConsurv has provided me a good platform to build my character and taught me to be human. Time passes faster and faster, but with every project I always want to find the next challenge and the next challenge is just as exciting as the previous one. Highlighted project that makes me become a stronger person was with Petrofac, a big company with 1001 stories inside and gratefully I was one of the main characters. Being screwed up with this project at the first time, taught me a lot of things especially in solving problems, persuasive, patience, responsibility, honesty with your boss, clients and suppliers and last but not least being a multitask person.",
      "The hard time that I went through was when I have been scolded with more than three staffs from Petrofac including from his boss, engineer and technician. At that moment, I really feel what is pressure and stress was all about. Sharing tears and stories with the staffs built up my positive energy with their motivations to face and solve this problem maturely as a woman. After almost 5 months, the problem solved and the status was completed. I do believe that, no matter where you are, no matter how difficult things might appear to be, you are always being moved toward magnificence. Always.",
      "Dear boss, as a supervisor you are truly an inspiration to me and your staffs. Thank you for everything and I feel lucky to be a part of your team. To all DynaConsurv staffs Fuad, Aaron, Lee, Kamarul, Husna, Nas, Nina, Linda, Jannah, Sundara, Amir, Zihan and Azfar thank you for your guidance, knowledge and made my journey at here more colourful. Last but not least to all my peers, Afiqah, Cuong, Frenchlyn, Kin, Azraai, Farahin, Steve and Jack thank you for always be there for me. Time passes. Memories fade. Feelings change. People leave. But the heart never forgets.",
    ],
  },
  {
    name: "Djamalladine Mahamat",
    image: "/testimonials/jamalladine.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Djamalladine-Mahamat-testimonials",
    para: [
      "My internship experience in Consurv Technic was one of (if not the only) influential moment (s) of my academic pursuit. Exposing me automated systems (RFID) paved the way for my current research interests in optimization and artificial intelligence. More than just a business entity, Consurv Technic represented for me an institution that boosted my confidence, exposed me to the industrial business environment, and matured my skills in software development.",
      "Prior to joining Consurv Technic, having heard of the scope of works expected from me, I was both excited and scared. The scope of the job (interacting with RFID devices) was new to me, fascinating, and gave me a leverage boast around my friends. On the other hand, having practically no prior knowledge on RFID, my greatest fear was to fail to perform and fit in the company (then located on the prestigious UBN tower).",
      "With the guidance of Mr. Faiz and a few sacrifices (of sleep time), I built up my confidence and fit in easily. The greatest gift I had, as an intern, was to have my works compared to those of an expert programmer (Mr. Afendi), while other firms tend to downgrade the importance of interns’ jobs; and for that, I am more than grateful.",
      "The internship program offered me a chance to experience works behind the desk and as a field operator. Working as a research programmer earned me a chance to develop my problem solving skills, expends my software engineering experience, and above all, apply my knowledge to real life problems. The internship program offered me a lot of field trips where I was exposed to industrial safety procedures in petrochemical factories, the operational activities, and most importantly, I was aware of the need for automation in such factories. My past works for an automated attendance system using RFID clearly influenced my current research interests in artificial intelligence.",
      "If I am asked to resume my internship experience in a few words, I would say: “I walk in the office as a shy and inexperienced young programmer (wearing white socks), and came out as a mature developer ready to leave a mark in the petroleum industry",
    ],
  },

  {
    name: "Siti Yazimah Hasmadi",
    image: "/testimonials/sitiyazimmah.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Siti-Yazimah-Hasmadi-testimonials",
    para: [
      "I've been working with Dyna Segmen for about eight months and the first time I arrived here, nobody at the office. Why? Because it was Sunday. I strongly believe that spending my time in Dyna would be very helpful for my future and career. I have heard about this company from the seniors who were here before and I am very happy that I made the best decision to be in here.",
      "Personally, in Consurv, it has an amazing and fun working environment that is unbelievable! I do learn loads of things that I never thought in class, such as business management, problem-solving, etc. Being in Dyna Segmen opens a lot of prospects to me; I meet numerous people around the world especially during exhibitions and meetings. The most remarkable experience is when I get the chance to go ‘overseas’ and open my eyes to see the real world. Thank you boss! I do love the company trip where we gather as one big family.",
      "The best thing about Dyna is having extremely friends and attentive staff who always made my day. Thank you to Mr. Faiz H. Hussin, my supportive supervisor who never gives up guiding me in every single step, Mr. Nasrul Annuar, indeed a good listener for me whenever I feel stressed with workloads and to ask about his opinions, he is the right person, Ms. Hafiza my beloved supervisor who assists me in doing most of my projects and always has wonderful stories to be shared. Again, thank you very much for your never-ending support and guidance. It is a great pleasure to have ‘uols’ around me.",
      "To my colleagues, Reen, Yus, and Kalai, you guys rock! To newbies, Anif, Eja, Mugi, and Angga, wish you all the best! And my last word, believe me, you won’t regret being part of Consurv and Dyna, and I really would like to come back again boss.",
    ],
  },

  {
    name: "Eliya Fariha",
    image: "/testimonials/eliya.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Eliya-Fariha-testimonials",
    para: [
      "Hi, to those readers. Here are my stories along the journey of Consurv Technic (M) Sdn Bhd. Being accepting here was a bless as I had learnt a lot the phase of being programmer. Building apps, web and also other technical stuffs that enrich my knowledge as technology background. Within this period also, I am very lucky to involve one of diamond wrapping project from Dyna Segment at Petronas Penapisan Melaka for a week. I was never expecting for having such exposure where we need to go to site and wrap the leaking pipe which was very dangerous and challenging jobs as engineer. Yeah, for IT background like me, it weird to set down at site and being a technical person and did check for materials as preparing of wrapping the pipe. There are bad and good news at site. Which one do you want to hear? *Sigh. I don’t know why I ask you guys. As it was my stories, I chose the bad news. Returning from the site, I had an allergy. Itches. Whether I went to clinic or not, it did not effect at all. Soon, as it came to worse, I am deciding to meet the specialist at KPJ, Ampang. Yezza, praise to Almighty, I am still survive from those allergy. Yet, it still return if I forgot to eat the medicine that prescribed from the specialist. As for good news, I have been friends with these four guys required Anwar, Amir, Abang Man and also Raj. A team always being a team right until the end. There was one moment when Anwar and I had left behind to remove the corrosion. Both of us were new learners. Did not realizing the hazards coming or did not know it really was, actually, there was a leakage through the pipe and the dripping water touch down the floor continuously. Both of us though it was dripping of raining as there was raining a moment ago. However, it was not. It’s Naphta!! If something happened, we might die due to explosion. And the place for Area 2, unit 23 was shut down for a while, we could not continue the wrapping the pipe and other people job also was instructed to stop as it was really really dangerous. After all, it was really such fresh memory when recalling the time.",
      "However, being a programmer I knew it wasn't easy. I hate to give hopes to people instead to independent myself to explore the knowledge. Why?? Because coding it is a phase of passion. I have come to the end of building the app until it come to an error again. As time flies, if I could choose the quote, I would choose the quote from Thomas Edison.",
      "I have not failed. I've just found 10,000 ways that won't work.",
      "Genius is one percent inspiration and ninety-nine percent perspiration.",
      "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
      "I am not a failure, I will continue my best although it hard. I need a break before continuing the challenge as my heart was already expired. See ya!",
      "Thanks to be kept in memoir; Fuad, Anwar, Osamah, Barath, Dalilah, Herbert, Zayne, Sam, Shita, Izwan, Linda, Jannah, En. Jihan, Mior, Mahathir, Law, Billy, Hosh, Rafique, Fitz, Pain, Faiz, Kamarul, Vin, Abu, Nash, Sundara, Abg Man, Nasri, Syaggy, Chew, Tasvir, Boss and Eric.",
    ],
  },

  {
    name: "Dineshganth Sandrakumaran",
    image: "/testimonials/dinesh.jpg",
    university: "Universiti Teknologi PETRONAS (UTP)",
    course: "Information Technology",
    intern: "8 months",
    slug: "Dineshganth-Sandrakumaran-testimonials",
    para: [
      "I started of my Industrial Training when I was appointed as an  Engineer at Consurv Technic (M) Sdn Bhd and 28 weeks flew by in a blink of eye here in my host company. My experience here as an IT Engineer was loaded with a lot of good times and bad times too. It would have been a lot harder without the assistances of some employees here in my host company who played a great role in educating me.",
      "Firstly, I would like to show my appreciation to my parents for always being there for me giving me great support and inspiration by giving me the chance to be able to experience the actual obstacles of life. All the lessons that they have given me has vastly made me into a more wise and responsible individual.",
      "The Managing Director of Consurv Technic, Mr. Faiz Hussin bin Hussin, has also been a great individual in making my internship period an adventurous experience. I would like to take this moment to thank him for giving me the opportunity to get the experience in this great journey during my internship period and also giving me advises on how to create self-betterment to improve myself in many different ways. The relationship between the staffs and the interns here are more like family than just a normal working colleague. I am would like to indicate my grateful to Mr. Fuad, Mr. Luqman, Mr. Vinesh, Mr. Sundara, Ms. Aqeelah, Mrs. Fathin and Ms Farahin. Not forgetting the other staffs in the organization who have helped and advised me like Mr. Nasrul, Mr. Kamarul, Mr. Azfar, Ms. Linda, Ms. Shuhailah and other interns as well.",
    ],
  },
];
